# Generated by Django 5.0.9 on 2024-12-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_id', models.CharField(editable=False, max_length=4, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название мебели')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='Цена (сум)')),
                ('video_link', models.URLField(verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('bedroom', 'Спальный гарнитур'), ('wardrobe', 'Шкаф'), ('bed', 'Кровати'), ('dresser', 'Трюмо и камоды'), ('hallway', 'Прихожая'), ('desk', 'Писменные столы'), ('coffee_table', 'Журнальный столик'), ('dining', 'Столы стулья'), ('sofa_local', 'Диваны местного производства'), ('sofa_import', 'Диваны импортные премиум класса')], default='bedroom', max_length=20, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='furniture_images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='furniture.furniture')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'Обработка'), ('completed', 'Сделанный'), ('cancelled', 'Отменено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.furniture')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
